import argparse
import os
import numpy as np
import pandas as pd
from stable_baselines3 import PPO
# from stable_baselines3.common.env_util import make_vec_env # Not used for single env for now

# Assuming trading_signal_env.py is in the same directory or PYTHONPATH
from trading_signal_env import TradingSignalEnv

def dummy_historical_data_generator(pair_symbol: str, num_rows: int = 2000): # Increased rows for more data
    """
    Generates a dummy pandas DataFrame for historical market data.
    The data includes OHLCV and 5 other dummy indicators to match shape=(10,).
    This data is static and generated once.
    """
    print(f"DummyHistoricalDataGenerator: Generating {num_rows} rows of data for {pair_symbol}")
    data = {
        'Open': np.random.rand(num_rows) * 100 + 1000,
        'High': np.random.rand(num_rows) * 50 + (np.random.rand(num_rows) * 100 + 1000) + 5, # High > Open
        'Low': (np.random.rand(num_rows) * 100 + 1000) - (np.random.rand(num_rows) * 50 + 5), # Low < Open
        'Close': np.random.rand(num_rows) * 100 + 1000,
        'Volume': np.random.rand(num_rows) * 10000 + 100,
        'RSI': np.random.rand(num_rows) * 100,            # Feature 6
        'MACD_signal': np.random.rand(num_rows) * 10 - 5, # Feature 7
        'BB_upper': (np.random.rand(num_rows) * 100 + 1000) + np.random.rand(num_rows) * 20 + 10, # Feature 8
        'BB_lower': (np.random.rand(num_rows) * 100 + 1000) - np.random.rand(num_rows) * 20 - 10, # Feature 9
        'Sentiment': np.random.rand(num_rows) * 2 - 1,     # Feature 10
        # New dummy features for LSTM and Bayesian LSTM predictions
        'lstm_pred': np.random.randn(num_rows) * 50 + (np.random.rand(num_rows) * 100 + 1000), # Feature 11 - centered around close
        'bayes_pred_mean': np.random.randn(num_rows) * 50 + (np.random.rand(num_rows) * 100 + 1000), # Feature 12 - centered around close
        'bayes_uncertainty': np.random.rand(num_rows) * 10 + 0.1 # Feature 13 - small positive values for uncertainty
    }
    df = pd.DataFrame(data)
    # Ensure Low is not higher than High (simple clamp)
    df['Low'] = np.minimum(df['Low'], df['Open'] - 1)
    df['Low'] = np.minimum(df['Low'], df['Close'] -1)
    df['High'] = np.maximum(df['High'], df['Open'] + 1)
    df['High'] = np.maximum(df['High'], df['Close'] + 1)
    df.index = pd.to_datetime(pd.date_range(start='2023-01-01', periods=num_rows, freq='1H'))
    return df

class StaticHistoricalDataProvider:
    """
    A simple data provider that holds a static DataFrame generated by
    `dummy_historical_data_generator`.
    This provider object is passed to the TradingSignalEnv.
    The environment will eventually need to be modified to call methods on this
    provider (e.g., in its reset and step methods) to get data and form observations.
    """
    def __init__(self, pair_symbol: str):
        self.pair_symbol = pair_symbol
        # Generate and store the data immediately on initialization
        self.data_frame = dummy_historical_data_generator(pair_symbol, num_rows=2000) # num_rows can be configurable
        print(f"StaticHistoricalDataProvider initialized for {pair_symbol} with {len(self.data_frame)} data points.")

    def get_historical_data(self, pair_symbol: str):
        """
        Returns the entire historical data DataFrame for the given pair symbol.
        Ignores pair_symbol for now as data is loaded for one symbol at init.
        """
        # In a more complex provider, pair_symbol would be used to select/fetch data.
        # Here, we assume the provider was initialized for the correct symbol.
        return self.data_frame

    def get_initial_observation_data_sample(self):
        """
        Returns a sample data row that matches the environment's observation space shape.
        This is useful for initializing the environment or for testing.
        The TradingSignalEnv currently uses np.zeros for observations, this method
        is a placeholder for how it *could* get real data.
        """
        if not self.data_frame.empty:
            # Return the first row's values as a numpy array of float32
            return self.data_frame.iloc[0].values.astype(np.float32)
        else:
            # Fallback if data frame is empty, though it shouldn't be with current generator
            return np.zeros(10, dtype=np.float32) # Matches shape (10,)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train PPO agent for trading signals.")
    parser.add_argument("--pair", type=str, required=True, help="Trading pair symbol (e.g., BTCUSDT)")
    parser.add_argument("--steps", type=int, default=50000, help="Total training timesteps (default: 50000)")
    parser.add_argument("--model_save_path", type=str, default="./best_models/", help="Path to save trained models (default: ./best_models/)")
    parser.add_argument("--log_path", type=str, default="./logs/rl_training_logs/", help="Path to save TensorBoard logs (default: ./logs/rl_training_logs/)")

    args = parser.parse_args()

    os.makedirs(args.model_save_path, exist_ok=True)
    os.makedirs(args.log_path, exist_ok=True)

    print(f"Starting training for pair: {args.pair} for {args.steps} timesteps.")
    print(f"Models will be saved to: {args.model_save_path}")
    print(f"TensorBoard logs will be saved to: {args.log_path}")

    # Instantiate the historical data provider.
    # This provider object will be passed to the environment.
    # The TradingSignalEnv is currently using placeholder observations (np.zeros).
    # In a future task, the environment will be updated to use this provider
    # to fetch data and form its observations.
    historical_data_provider = StaticHistoricalDataProvider(args.pair)

    # Instantiate the custom trading environment
    env = TradingSignalEnv(
        pair_symbol=args.pair,
        historical_data_provider=historical_data_provider, # Pass the provider instance
        initial_balance=10000.0,
        fee_percentage=0.001,
        max_episode_steps=1000 # Number of steps in one episode before truncation
    )
    
    print(f"TradingSignalEnv instantiated for {args.pair}.")
    print(f"Action Space: {env.action_space}")
    print(f"Observation Space: {env.observation_space} (Note: Current env implementation uses dummy np.zeros observations)")

    # Instantiate the PPO agent
    model = PPO(
        "MlpPolicy",
        env,
        verbose=1,
        tensorboard_log=args.log_path,
        device="auto" # Automatically uses GPU if available, else CPU
    )
    print("PPO model instantiated.")

    # Train the agent
    print(f"Starting model training for {args.steps} timesteps...")
    # tb_log_name will create a sub-folder within args.log_path for this specific run
    model.learn(total_timesteps=args.steps, tb_log_name=f"PPO_{args.pair.replace('/','_')}") # Sanitize pair name for filesystem
    print("Model training completed.")

    # Construct the model filename and save the trained model
    # Sanitize pair name for the filename (e.g., replace '/' with '_')
    sanitized_pair_name = args.pair.replace('/', '_').lower()
    model_filename = f"{sanitized_pair_name}_ppo_trading_signal_model.zip"
    model_full_path = os.path.join(args.model_save_path, model_filename)
    
    model.save(model_full_path)

    print(f"Trained model saved to: {model_full_path}")
    print("--------------------------------------------------------------------")
    print("To view TensorBoard logs, run the following command in your terminal:")
    print(f"tensorboard --logdir={os.path.abspath(args.log_path)}")
    print("--------------------------------------------------------------------")
    print("Training script finished successfully.")
    print("Important Note: The TradingSignalEnv currently uses placeholder (zeroed) observations and a basic reward structure.")
    print("Meaningful learning requires updating the environment to process data from the historical_data_provider and implement a relevant reward function.")

    # Example run command from the terminal:
    # python train_trading_signal_rl.py --pair BTCUSDT --steps 20000
    # (Steps are moderate as the env is not yet learning meaningfully)
